var memes = [
  {
    id: 1,
    slug: "demo-meme-01",
    name: "Demo Meme 01",
    aliases: ["demo 01", "demo meme 01"],
    image: "./assets/images/demo-01.svg",
    oneLineDescription: "데모용 플레이스홀더 밈입니다. 실제 유행 정보가 아닙니다.",
    description: "이 항목은 그리드·필터·검색·상세 화면을 검증하기 위한 샘플 데이터입니다.",
    whyTrending: "실제 트렌드가 아니라 MVP 화면을 채우기 위해 표시됩니다.",
    usage: ["검색 테스트", "카드 클릭 테스트", "상세 화면 순서 확인"],
    keywords: ["demo", "placeholder", "01"],
    hashtags: ["#demo", "#memesearcher"],
    countries: ["global", "us", "china", "korea", "japan"],
    status: "popular",
    popularityScore: 96,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2001",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2001",
      x: "https://x.com/search?q=Demo%20Meme%2001",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2001"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 2,
    slug: "demo-meme-02",
    name: "Demo Meme 02",
    aliases: ["demo 02"],
    image: "./assets/images/demo-02.svg",
    oneLineDescription: "미국 중심의 데모 급상승 밈 샘플입니다.",
    description: "국가 필터와 상태 필터가 함께 적용되는지 확인하기 위한 데이터입니다.",
    whyTrending: "데모 데이터이므로 실제 유행 이유가 없습니다.",
    usage: ["미국 + 급상승 필터 확인", "카드 레이아웃 확인"],
    keywords: ["demo", "us", "rising"],
    hashtags: ["#demo02"],
    countries: ["us"],
    status: "rising",
    popularityScore: 88,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2002",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2002",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 3,
    slug: "demo-meme-03",
    name: "Demo Meme 03",
    aliases: ["demo 03"],
    image: "./assets/images/demo-03.svg",
    oneLineDescription: "미국 신규 밈을 나타내는 플레이스홀더입니다.",
    description: "신규 필터가 상태값 new 만 남기는지 확인합니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["미국 + 신규 필터"],
    keywords: ["demo", "new", "us"],
    hashtags: ["#demo03"],
    countries: ["us"],
    status: "new",
    popularityScore: 54,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2003"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 4,
    slug: "demo-meme-04",
    name: "Demo Meme 04",
    aliases: ["demo 04"],
    image: "./assets/images/demo-04.svg",
    oneLineDescription: "미국 인기 밈 샘플입니다.",
    description: "인기 상태 필터 검증용 데이터입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["미국 + 인기 필터"],
    keywords: ["demo", "popular"],
    hashtags: ["#demo04"],
    countries: ["us"],
    status: "popular",
    popularityScore: 91,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2004",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2004",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 5,
    slug: "demo-meme-05",
    name: "Demo Meme 05",
    aliases: ["demo 05", "korea rising"],
    image: "./assets/images/demo-05.svg",
    oneLineDescription: "한국 급상승 필터 테스트용 데모 밈입니다.",
    description: "한국을 고른 뒤 급상승을 누르면 이 카드가 남아야 합니다.",
    whyTrending: "필터 조합 테스트를 위해 급상승으로 표시했습니다.",
    usage: ["한국 필터", "급상승 필터", "상세 화면 진입"],
    keywords: ["demo", "korea", "rising"],
    hashtags: ["#demo05"],
    countries: ["korea"],
    status: "rising",
    popularityScore: 84,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2005",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2005",
      x: "https://x.com/search?q=Demo%20Meme%2005",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2005"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 6,
    slug: "demo-meme-06",
    name: "Demo Meme 06",
    aliases: ["demo 06"],
    image: "./assets/images/demo-06.svg",
    oneLineDescription: "두 번째 한국 급상승 데모 밈입니다.",
    description: "한국 + 급상승 결과에 최소 두 장이 보이도록 넣은 샘플입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["한국 + 급상승"],
    keywords: ["demo", "korea"],
    hashtags: ["#demo06"],
    countries: ["korea"],
    status: "rising",
    popularityScore: 79,
    platformLinks: {
      tiktok: "",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2006",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 7,
    slug: "demo-meme-07",
    name: "Demo Meme 07",
    aliases: ["demo 07"],
    image: "./assets/images/demo-07.svg",
    oneLineDescription: "한국 인기 밈 샘플입니다.",
    description: "급상승이 아닌 인기 상태라 한국+급상승에서는 빠져야 합니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["한국 + 인기"],
    keywords: ["demo", "korea", "popular"],
    hashtags: ["#demo07"],
    countries: ["korea"],
    status: "popular",
    popularityScore: 90,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2007",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2007",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 8,
    slug: "demo-meme-08",
    name: "Demo Meme 08",
    aliases: ["demo 08"],
    image: "./assets/images/demo-08.svg",
    oneLineDescription: "한국 신규 밈 샘플입니다.",
    description: "신규 필터 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["한국 + 신규"],
    keywords: ["demo", "korea", "new"],
    hashtags: ["#demo08"],
    countries: ["korea"],
    status: "new",
    popularityScore: 61,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 9,
    slug: "demo-meme-09",
    name: "Demo Meme 09",
    aliases: ["demo 09"],
    image: "./assets/images/demo-09.svg",
    oneLineDescription: "한국에서 보이는 또 다른 인기 데모 밈입니다.",
    description: "한국 필터에 여러 장이 쌓이도록 넣은 샘플입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["한국 그리드 확인"],
    keywords: ["demo", "korea"],
    hashtags: ["#demo09"],
    countries: ["korea"],
    status: "popular",
    popularityScore: 86,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2009",
      instagram: "",
      x: "",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2009"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 10,
    slug: "demo-meme-10",
    name: "Demo Meme 10",
    aliases: ["demo 10", "japan rising"],
    image: "./assets/images/demo-10.svg",
    oneLineDescription: "일본 급상승 데모 밈입니다.",
    description: "일본 필터와 검색 시 전체 전환을 확인하는 데 씁니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 필터 후 검색하면 전체로 이동"],
    keywords: ["demo", "japan", "brainrot"],
    hashtags: ["#demo10"],
    countries: ["japan"],
    status: "rising",
    popularityScore: 83,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2010",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2010",
      x: "https://x.com/search?q=Demo%20Meme%2010",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 11,
    slug: "demo-meme-11",
    name: "Demo Meme 11",
    aliases: ["demo 11"],
    image: "./assets/images/demo-11.svg",
    oneLineDescription: "일본 인기 밈 샘플입니다.",
    description: "일본 인기 필터 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 + 인기"],
    keywords: ["demo", "japan"],
    hashtags: ["#demo11"],
    countries: ["japan"],
    status: "popular",
    popularityScore: 89,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2011",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 12,
    slug: "demo-meme-12",
    name: "Demo Meme 12",
    aliases: ["demo 12"],
    image: "./assets/images/demo-12.svg",
    oneLineDescription: "일본 신규 밈 샘플입니다.",
    description: "일본 신규 필터 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 + 신규"],
    keywords: ["demo", "japan", "new"],
    hashtags: ["#demo12"],
    countries: ["japan"],
    status: "new",
    popularityScore: 58,
    platformLinks: {
      tiktok: "",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2012",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 13,
    slug: "demo-meme-13",
    name: "Demo Meme 13",
    aliases: ["demo 13"],
    image: "./assets/images/demo-13.svg",
    oneLineDescription: "일본에서 보이는 두 번째 급상승 샘플입니다.",
    description: "일본 그리드가 비지 않도록 넣은 데이터입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 + 급상승"],
    keywords: ["demo", "japan"],
    hashtags: ["#demo13"],
    countries: ["japan"],
    status: "rising",
    popularityScore: 77,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2013",
      instagram: "",
      x: "",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2013"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 14,
    slug: "demo-meme-14",
    name: "Demo Meme 14",
    aliases: ["demo 14"],
    image: "./assets/images/demo-14.svg",
    oneLineDescription: "중국 인기 밈 샘플입니다.",
    description: "중국 필터 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["중국 + 인기"],
    keywords: ["demo", "china"],
    hashtags: ["#demo14"],
    countries: ["china"],
    status: "popular",
    popularityScore: 87,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2014",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 15,
    slug: "demo-meme-15",
    name: "Demo Meme 15",
    aliases: ["demo 15"],
    image: "./assets/images/demo-15.svg",
    oneLineDescription: "중국 급상승 밈 샘플입니다.",
    description: "중국 + 급상승 조합 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["중국 + 급상승"],
    keywords: ["demo", "china", "rising"],
    hashtags: ["#demo15"],
    countries: ["china"],
    status: "rising",
    popularityScore: 81,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2015",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2015"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 16,
    slug: "demo-meme-16",
    name: "Demo Meme 16",
    aliases: ["demo 16"],
    image: "./assets/images/demo-16.svg",
    oneLineDescription: "중국 신규 밈 샘플입니다.",
    description: "중국 신규 필터 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["중국 + 신규"],
    keywords: ["demo", "china", "new"],
    hashtags: ["#demo16"],
    countries: ["china"],
    status: "new",
    popularityScore: 52,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 17,
    slug: "demo-meme-17",
    name: "Demo Meme 17",
    aliases: ["demo 17"],
    image: "./assets/images/demo-17.svg",
    oneLineDescription: "중국에서 보이는 두 번째 인기 샘플입니다.",
    description: "중국 그리드 밀도 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["중국 필터"],
    keywords: ["demo", "china"],
    hashtags: ["#demo17"],
    countries: ["china"],
    status: "popular",
    popularityScore: 85,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2017",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2017",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 18,
    slug: "demo-meme-18",
    name: "Demo Meme 18",
    aliases: ["demo 18"],
    image: "./assets/images/demo-18.svg",
    oneLineDescription: "미국 급상승 두 번째 샘플입니다.",
    description: "미국 그리드가 한 장만 보이지 않도록 넣었습니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["미국 + 급상승"],
    keywords: ["demo", "us"],
    hashtags: ["#demo18"],
    countries: ["us"],
    status: "rising",
    popularityScore: 80,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2018",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2018",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2018"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 19,
    slug: "demo-meme-19",
    name: "Demo Meme 19",
    aliases: ["demo 19"],
    image: "./assets/images/demo-19.svg",
    oneLineDescription: "미국과 한국에 동시에 나타나는 신규 샘플입니다.",
    description: "여러 국가 배열을 가진 데이터가 각 필터에 포함되는지 확인합니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["미국 필터", "한국 필터"],
    keywords: ["demo", "us", "korea"],
    hashtags: ["#demo19"],
    countries: ["us", "korea"],
    status: "new",
    popularityScore: 63,
    platformLinks: {
      tiktok: "",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2019",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 20,
    slug: "demo-meme-20",
    name: "Demo Meme 20",
    aliases: ["demo 20"],
    image: "./assets/images/demo-20.svg",
    oneLineDescription: "일본과 중국에 동시에 나타나는 인기 샘플입니다.",
    description: "다중 국가 데이터의 필터 포함 여부를 확인합니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 필터", "중국 필터"],
    keywords: ["demo", "japan", "china"],
    hashtags: ["#demo20"],
    countries: ["japan", "china"],
    status: "popular",
    popularityScore: 82,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2020",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 21,
    slug: "demo-meme-21",
    name: "Demo Meme 21",
    aliases: ["demo 21"],
    image: "./assets/images/demo-21.svg",
    oneLineDescription: "7일 기간에서만 보이도록 날짜를 다르게 둔 샘플입니다.",
    description: "24H와 7D 기간 토글을 확인하기 위한 데이터입니다.",
    whyTrending: "기간 필터 테스트용입니다.",
    usage: ["7D 선택 후 목록에 나타나는지 확인"],
    keywords: ["demo", "period", "7d"],
    hashtags: ["#demo21"],
    countries: ["global", "us", "china", "korea", "japan"],
    status: "new",
    popularityScore: 49,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2021",
      youtube: ""
    },
    createdAt: "2026-08-10"
  },
  {
    id: 22,
    slug: "demo-meme-22",
    name: "Demo Meme 22",
    aliases: ["demo 22"],
    image: "./assets/images/demo-22.svg",
    oneLineDescription: "한국 급상승이지만 24시간이 지난 샘플입니다.",
    description: "한국 + 급상승 + 7D 조합에서 추가로 보여야 합니다.",
    whyTrending: "기간 필터 테스트용입니다.",
    usage: ["7D + 한국 + 급상승"],
    keywords: ["demo", "korea", "7d"],
    hashtags: ["#demo22"],
    countries: ["korea"],
    status: "rising",
    popularityScore: 74,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2022",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-09"
  },
  {
    id: 23,
    slug: "demo-meme-23",
    name: "Demo Meme 23",
    aliases: ["demo 23"],
    image: "./assets/images/demo-23.svg",
    oneLineDescription: "미국 인기 밈 추가 샘플입니다.",
    description: "4열 그리드가 여러 줄로 이어지는지 확인합니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["그리드 줄 수 확인"],
    keywords: ["demo", "us"],
    hashtags: ["#demo23"],
    countries: ["us"],
    status: "popular",
    popularityScore: 88,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2023"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 24,
    slug: "demo-meme-24",
    name: "Demo Meme 24",
    aliases: ["demo 24"],
    image: "./assets/images/demo-24.svg",
    oneLineDescription: "일본 신규 밈 추가 샘플입니다.",
    description: "일본 목록이 너무 짧지 않게 넣었습니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["일본 필터"],
    keywords: ["demo", "japan"],
    hashtags: ["#demo24"],
    countries: ["japan"],
    status: "new",
    popularityScore: 57,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2024",
      instagram: "",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 25,
    slug: "demo-meme-25",
    name: "Demo Meme 25",
    aliases: ["demo 25"],
    image: "./assets/images/demo-25.svg",
    oneLineDescription: "중국 급상승 추가 샘플입니다.",
    description: "중국 급상승 목록 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["중국 + 급상승"],
    keywords: ["demo", "china"],
    hashtags: ["#demo25"],
    countries: ["china"],
    status: "rising",
    popularityScore: 76,
    platformLinks: {
      tiktok: "",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2025",
      x: "",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 26,
    slug: "demo-meme-26",
    name: "Demo Meme 26",
    aliases: ["demo 26"],
    image: "./assets/images/demo-26.svg",
    oneLineDescription: "여러 국가에 걸친 인기 데모 밈입니다.",
    description: "전체 필터에서 상위에 섞여 보이도록 넣었습니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["전체 그리드", "한국/일본 필터"],
    keywords: ["demo", "global"],
    hashtags: ["#demo26"],
    countries: ["global", "korea", "japan"],
    status: "popular",
    popularityScore: 93,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2026",
      instagram: "https://www.instagram.com/explore/search/keyword/?q=Demo%20Meme%2026",
      x: "https://x.com/search?q=Demo%20Meme%2026",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2026"
    },
    createdAt: "2026-08-14"
  },
  {
    id: 27,
    slug: "demo-meme-27",
    name: "Demo Meme 27",
    aliases: ["demo 27"],
    image: "./assets/images/demo-27.svg",
    oneLineDescription: "미국과 중국의 신규 샘플입니다.",
    description: "다중 국가 + 신규 상태 확인용입니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["미국 + 신규", "중국 + 신규"],
    keywords: ["demo", "us", "china"],
    hashtags: ["#demo27"],
    countries: ["us", "china"],
    status: "new",
    popularityScore: 60,
    platformLinks: {
      tiktok: "",
      instagram: "",
      x: "https://x.com/search?q=Demo%20Meme%2027",
      youtube: ""
    },
    createdAt: "2026-08-14"
  },
  {
    id: 28,
    slug: "demo-meme-28",
    name: "Demo Meme 28",
    aliases: ["demo 28"],
    image: "./assets/images/demo-28.svg",
    oneLineDescription: "한국과 일본에 동시에 보이는 인기 샘플입니다.",
    description: "검색어 demo 28 로 찾을 수 있습니다.",
    whyTrending: "샘플 데이터입니다.",
    usage: ["검색 테스트", "한국/일본 필터"],
    keywords: ["demo", "korea", "japan"],
    hashtags: ["#demo28"],
    countries: ["korea", "japan"],
    status: "popular",
    popularityScore: 84,
    platformLinks: {
      tiktok: "https://www.tiktok.com/search?q=Demo%20Meme%2028",
      instagram: "",
      x: "",
      youtube: "https://www.youtube.com/results?search_query=Demo%20Meme%2028"
    },
    createdAt: "2026-08-14"
  }
];
